# rewrite_status: rewritten
#title: Viennese composers and their compositions by tonality
#defaultView:Tree
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>

SELECT  ?composer ?composerLabel ?composerImage ?tonality ?tonalityLabel ?composition ?compositionLabel
WHERE
  { ?composer  wdt:P31  wd:Q5 .
    ?composer (wdt:P19|wdt:P20)|wdt:P551 wd:Q1741
    OPTIONAL
      { ?composer  wdt:P18  ?composerImage }
    ?composition  wdt:P86  ?composer ;
              wdt:P826  ?tonality
    OPTIONAL
      { ?composer  rdfs:label  ?composer__label_value
        FILTER ( lang(?composer__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?composer  rdfs:label  ?composer__label_value
        FILTER ( lang(?composer__label_value) = "de-at" )
      }
    OPTIONAL
      { ?composer  rdfs:label  ?composer__label_value
        FILTER ( lang(?composer__label_value) = "de" )
      }
    OPTIONAL
      { ?composer  rdfs:label  ?composer__label_value
        FILTER ( lang(?composer__label_value) = "mul" )
      }
    BIND(if(bound(?composer__label_value), ?composer__label_value, if(( isURI(?composer) && strstarts(str(?composer), "http://www.wikidata.org/entity/") ), strafter(str(?composer), "entity/"), str(?composer))) AS ?composerLabel)
    OPTIONAL
      { ?tonality  rdfs:label  ?tonality__label_value
        FILTER ( lang(?tonality__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?tonality  rdfs:label  ?tonality__label_value
        FILTER ( lang(?tonality__label_value) = "de-at" )
      }
    OPTIONAL
      { ?tonality  rdfs:label  ?tonality__label_value
        FILTER ( lang(?tonality__label_value) = "de" )
      }
    OPTIONAL
      { ?tonality  rdfs:label  ?tonality__label_value
        FILTER ( lang(?tonality__label_value) = "mul" )
      }
    BIND(if(bound(?tonality__label_value), ?tonality__label_value, if(( isURI(?tonality) && strstarts(str(?tonality), "http://www.wikidata.org/entity/") ), strafter(str(?tonality), "entity/"), str(?tonality))) AS ?tonalityLabel)
    OPTIONAL
      { ?composition  rdfs:label  ?composition__label_value
        FILTER ( lang(?composition__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?composition  rdfs:label  ?composition__label_value
        FILTER ( lang(?composition__label_value) = "de-at" )
      }
    OPTIONAL
      { ?composition  rdfs:label  ?composition__label_value
        FILTER ( lang(?composition__label_value) = "de" )
      }
    OPTIONAL
      { ?composition  rdfs:label  ?composition__label_value
        FILTER ( lang(?composition__label_value) = "mul" )
      }
    BIND(if(bound(?composition__label_value), ?composition__label_value, if(( isURI(?composition) && strstarts(str(?composition), "http://www.wikidata.org/entity/") ), strafter(str(?composition), "entity/"), str(?composition))) AS ?compositionLabel)
  }
ORDER BY ?composerLabel ?tonalityLabel

# Original query:
# #title: Viennese composers and their compositions by tonality
# #defaultView:Tree
# SELECT ?composer ?composerLabel ?composerImage ?tonality ?tonalityLabel ?composition ?compositionLabel WHERE {
#   ?composer wdt:P31 wd:Q5;
#             wdt:P19|wdt:P20|wdt:P551 wd:Q1741.
#   OPTIONAL { ?composer wdt:P18 ?composerImage. }
#   ?composition wdt:P86 ?composer;
#                wdt:P826 ?tonality.
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de-at,de". }
# }
# ORDER BY ?composerLabel ?tonalityLabel
