# rewrite_status: rewritten
#title: Properties likely missing type constraints
# All properties whose values are items and which lack a type constraint and property scope constraint.
# Some of these may be actually general properties, while others just don't have their relevant type constraint defined yet.
#
# The lack of property scope constraint just identifies high priority ones, as that constraint is always required,
# so if it is missing, it makes it more likely that there is a reasonable type constraint that just hasn't been defined.

PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  schema: <http://schema.org/>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>
PREFIX  wikibase: <http://wikiba.se/ontology#>

SELECT  ?property (GROUP_CONCAT(?propertyCategoryLabel ; separator='; ') AS ?categories) ?propertyLabel ?propertyDescription ?propertyAltLabel
WHERE
  { { SELECT  ?property ?propertyCategoryLabel ?propertyLabel ?propertyDescription ?propertyAltLabel
      WHERE
        { ?property  wikibase:propertyType  wikibase:WikibaseItem
          MINUS
            { ?property  wdt:P2302  wd:Q21503250 }
          MINUS
            { ?property  wdt:P2302  wd:Q53869507 }
          OPTIONAL
            { ?property  wdt:P31  ?propertyCategory }
          OPTIONAL
            { ?property  rdfs:label  ?property__label_value
              FILTER ( lang(?property__label_value) = "[AUTO_LANGUAGE]" )
            }
          OPTIONAL
            { ?property  rdfs:label  ?property__label_value
              FILTER ( lang(?property__label_value) = "mul" )
            }
          OPTIONAL
            { ?property  rdfs:label  ?property__label_value
              FILTER ( lang(?property__label_value) = "en" )
            }
          BIND(if(bound(?property__label_value), ?property__label_value, if(( isURI(?property) && strstarts(str(?property), "http://www.wikidata.org/entity/") ), strafter(str(?property), "entity/"), str(?property))) AS ?propertyLabel)
          OPTIONAL
            { ?property  schema:description  ?property__description_value
              FILTER ( lang(?property__description_value) = "[AUTO_LANGUAGE]" )
            }
          OPTIONAL
            { ?property  schema:description  ?property__description_value
              FILTER ( lang(?property__description_value) = "en" )
            }
          BIND(?property__description_value AS ?propertyDescription)
          OPTIONAL
            { SELECT  ?property (GROUP_CONCAT(DISTINCT ?property__alias_value ; separator=', ') AS ?propertyAltLabel)
              WHERE
                { { SELECT  ?property
                    WHERE
                      { ?property  wikibase:propertyType  wikibase:WikibaseItem
                        OPTIONAL
                          { ?property  wdt:P31  ?propertyCategory }
                      }
                  }
                  OPTIONAL
                    { ?property  skos:altLabel  ?property__alias_value
                      FILTER ( lang(?property__alias_value) = "[AUTO_LANGUAGE]" )
                    }
                  OPTIONAL
                    { ?property  skos:altLabel  ?property__alias_value
                      FILTER ( lang(?property__alias_value) = "mul" )
                    }
                  OPTIONAL
                    { ?property  skos:altLabel  ?property__alias_value
                      FILTER ( lang(?property__alias_value) = "en" )
                    }
                }
              GROUP BY ?property
            }
          BIND(if(bound(?propertyCategory), ?propertyCategory, "unbound") AS ?propertyCategory__label_subject)
          OPTIONAL
            { ?propertyCategory__label_subject
                        rdfs:label  ?propertyCategory__label_value
              FILTER ( lang(?propertyCategory__label_value) = "[AUTO_LANGUAGE]" )
            }
          OPTIONAL
            { ?propertyCategory__label_subject
                        rdfs:label  ?propertyCategory__label_value
              FILTER ( lang(?propertyCategory__label_value) = "mul" )
            }
          OPTIONAL
            { ?propertyCategory__label_subject
                        rdfs:label  ?propertyCategory__label_value
              FILTER ( lang(?propertyCategory__label_value) = "en" )
            }
          BIND(if(bound(?propertyCategory__label_value), ?propertyCategory__label_value, if(( isURI(?propertyCategory) && strstarts(str(?propertyCategory), "http://www.wikidata.org/entity/") ), strafter(str(?propertyCategory), "entity/"), str(?propertyCategory))) AS ?propertyCategoryLabel)
        }
    }
  }
GROUP BY ?property ?propertyLabel ?propertyDescription ?propertyAltLabel

# Original query:
# #title: Properties likely missing type constraints
# # All properties whose values are items and which lack a type constraint and property scope constraint.
# # Some of these may be actually general properties, while others just don't have their relevant type constraint defined yet.
# #
# # The lack of property scope constraint just identifies high priority ones, as that constraint is always required,
# # so if it is missing, it makes it more likely that there is a reasonable type constraint that just hasn't been defined.
#
# SELECT ?property (GROUP_CONCAT(?propertyCategoryLabel; SEPARATOR = "; ") AS ?categories) ?propertyLabel ?propertyDescription ?propertyAltLabel WHERE {
#   {
#     SELECT ?property ?propertyCategoryLabel ?propertyLabel ?propertyDescription ?propertyAltLabel WHERE {
#       ?property wikibase:propertyType wikibase:WikibaseItem.
#       MINUS { ?property wdt:P2302 wd:Q21503250. }
#       MINUS { ?property wdt:P2302 wd:Q53869507. }
#       OPTIONAL { ?property wdt:P31 ?propertyCategory. }
#       SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
#     }
#   }
# }
# GROUP BY ?property ?propertyLabel ?propertyDescription ?propertyAltLabel
