# rewrite_status: rewritten
#title: Sandwiches
#defaultView:ImageGrid
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>

SELECT  ?item ?itemLabel ?_image
WHERE
  { ?item  wdt:P279  wd:Q28803
    OPTIONAL
      { ?item  wdt:P18  ?_image }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "en" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "mul" )
      }
    BIND(if(bound(?item__label_value), ?item__label_value, if(( isURI(?item) && strstarts(str(?item), "http://www.wikidata.org/entity/") ), strafter(str(?item), "entity/"), str(?item))) AS ?itemLabel)
  }
LIMIT   100

# Original query:
# #title: Sandwiches
# #defaultView:ImageGrid
# SELECT ?item ?itemLabel ?_image
# WHERE
# {
#   ?item wdt:P279 wd:Q28803.
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
# OPTIONAL { ?item wdt:P18 ?_image. }
# }
# LIMIT 100
