# rewrite_status: rewritten
#title: American universities founded before the states they reside in were created
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>

SELECT  ?uLabel ?founded ?stateLabel ?stateStart
WHERE
  { ?u wdt:P31/(wdt:P279)* wd:Q3918 .
    ?u (wdt:P131)+ ?state .
    ?u      wdt:P571  ?founded .
    ?state  wdt:P31   wd:Q35657 ;
            wdt:P571  ?stateStart
    FILTER ( ?founded < ?stateStart )
    OPTIONAL
      { ?u  rdfs:label  ?u__label_value
        FILTER ( lang(?u__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?u  rdfs:label  ?u__label_value
        FILTER ( lang(?u__label_value) = "mul" )
      }
    OPTIONAL
      { ?u  rdfs:label  ?u__label_value
        FILTER ( lang(?u__label_value) = "en" )
      }
    BIND(if(bound(?u__label_value), ?u__label_value, if(( isURI(?u) && strstarts(str(?u), "http://www.wikidata.org/entity/") ), strafter(str(?u), "entity/"), str(?u))) AS ?uLabel)
    OPTIONAL
      { ?state  rdfs:label  ?state__label_value
        FILTER ( lang(?state__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?state  rdfs:label  ?state__label_value
        FILTER ( lang(?state__label_value) = "mul" )
      }
    OPTIONAL
      { ?state  rdfs:label  ?state__label_value
        FILTER ( lang(?state__label_value) = "en" )
      }
    BIND(if(bound(?state__label_value), ?state__label_value, if(( isURI(?state) && strstarts(str(?state), "http://www.wikidata.org/entity/") ), strafter(str(?state), "entity/"), str(?state))) AS ?stateLabel)
  }
LIMIT   10

# Original query:
# #title: American universities founded before the states they reside in were created
# SELECT ?uLabel ?founded ?stateLabel ?stateStart
# WHERE {
#   ?u wdt:P31/wdt:P279* wd:Q3918 ;
#        wdt:P131+ ?state ;
#        wdt:P571 ?founded .
#   ?state wdt:P31 wd:Q35657 ;
#            wdt:P571 ?stateStart .
#   FILTER (?founded < ?stateStart) .
#   SERVICE wikibase:label {
#     bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en".
#   }
# }
# LIMIT 10
