# rewrite_status: rewritten
#title: Biological databases listed in Wikidata and, if available, applicable licenses
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>

SELECT  ?item ?itemLabel ?url ?licence ?licenceLabel
WHERE
  { ?item  wdt:P31  wd:Q4117139
    OPTIONAL
      { ?item  wdt:P856  ?url }
    OPTIONAL
      { ?item  wdt:P275  ?licence }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "mul" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "en" )
      }
    BIND(if(bound(?item__label_value), ?item__label_value, if(( isURI(?item) && strstarts(str(?item), "http://www.wikidata.org/entity/") ), strafter(str(?item), "entity/"), str(?item))) AS ?itemLabel)
    BIND(if(bound(?licence), ?licence, "unbound") AS ?licence__label_subject)
    OPTIONAL
      { ?licence__label_subject
                  rdfs:label  ?licence__label_value
        FILTER ( lang(?licence__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?licence__label_subject
                  rdfs:label  ?licence__label_value
        FILTER ( lang(?licence__label_value) = "mul" )
      }
    OPTIONAL
      { ?licence__label_subject
                  rdfs:label  ?licence__label_value
        FILTER ( lang(?licence__label_value) = "en" )
      }
    BIND(if(bound(?licence__label_value), ?licence__label_value, if(( isURI(?licence) && strstarts(str(?licence), "http://www.wikidata.org/entity/") ), strafter(str(?licence), "entity/"), str(?licence))) AS ?licenceLabel)
  }
ORDER BY ?itemLabel

# Original query:
# #title: Biological databases listed in Wikidata and, if available, applicable licenses
# SELECT ?item ?itemLabel ?url ?licence ?licenceLabel
# WHERE {
#   ?item wdt:P31 wd:Q4117139.
#   OPTIONAL { ?item wdt:P856 ?url }
#   OPTIONAL { ?item wdt:P275 ?licence }
# SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" }
# } ORDER BY ?itemLabel
