# rewrite_status: rewritten
#title: Lexemes describing a color
# By Vesihiisi

PREFIX  dct:  <http://purl.org/dc/terms/>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>
PREFIX  wikibase: <http://wikiba.se/ontology#>

SELECT  ?l ?lemma ?languageLabel
WHERE
  { ?l  dct:language    ?language ;
        wikibase:lemma  ?lemma ;
        wdt:P31         wd:Q376431
    OPTIONAL
      { ?language  rdfs:label  ?language__label_value
        FILTER ( lang(?language__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?language  rdfs:label  ?language__label_value
        FILTER ( lang(?language__label_value) = "mul" )
      }
    OPTIONAL
      { ?language  rdfs:label  ?language__label_value
        FILTER ( lang(?language__label_value) = "en" )
      }
    BIND(if(bound(?language__label_value), ?language__label_value, if(( isURI(?language) && strstarts(str(?language), "http://www.wikidata.org/entity/") ), strafter(str(?language), "entity/"), str(?language))) AS ?languageLabel)
  }
ORDER BY ?languageLabel

# Original query:
# #title: Lexemes describing a color
# # By Vesihiisi
#
# SELECT ?l ?lemma ?languageLabel WHERE {
#   ?l dct:language ?language;
#      wikibase:lemma ?lemma;
#      wdt:P31 wd:Q376431.
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
# }
# ORDER BY ?languageLabel
