# rewrite_status: rewritten
#title: Map of hackerspaces using country as color
#defaultView:Map{"layer":"?countryLabel", "hide":["?geo"]}
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT  ?item ?itemLabel ?geo ?countryLabel
WHERE
  { ?item  wdt:P31   wd:Q1032372 ;
           wdt:P625  ?geo ;
           wdt:P17   ?country
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "mul" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "en" )
      }
    BIND(if(bound(?item__label_value), ?item__label_value, if(( isURI(?item) && strstarts(str(?item), "http://www.wikidata.org/entity/") ), strafter(str(?item), "entity/"), str(?item))) AS ?itemLabel)
    OPTIONAL
      { ?country  rdfs:label  ?country__label_value
        FILTER ( lang(?country__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?country  rdfs:label  ?country__label_value
        FILTER ( lang(?country__label_value) = "mul" )
      }
    OPTIONAL
      { ?country  rdfs:label  ?country__label_value
        FILTER ( lang(?country__label_value) = "en" )
      }
    BIND(if(bound(?country__label_value), ?country__label_value, if(( isURI(?country) && strstarts(str(?country), "http://www.wikidata.org/entity/") ), strafter(str(?country), "entity/"), str(?country))) AS ?countryLabel)
  }
ORDER BY ?countryLabel

# Original query:
# #title: Map of hackerspaces using country as color
# #defaultView:Map{"layer":"?countryLabel", "hide":["?geo"]}
# SELECT DISTINCT ?item ?itemLabel ?geo ?countryLabel WHERE {
#   ?item wdt:P31 wd:Q1032372;
#         wdt:P625 ?geo ;
#         wdt:P17 ?country.
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
# } ORDER BY ?countryLabel
