# rewrite_status: rewritten
#defaultView:Map
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>

SELECT  ?label ?coord ?place ?image
WHERE
  { ?place  wdt:P31   wd:Q14276458 ;
            wdt:P186  wd:Q22731 ;
            wdt:P625  ?coord
    OPTIONAL
      { ?place  wdt:P18  ?image }
    OPTIONAL
      { ?place  rdfs:label  ?place__label_value
        FILTER ( lang(?place__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?place  rdfs:label  ?place__label_value
        FILTER ( lang(?place__label_value) = "en" )
      }
    OPTIONAL
      { ?place  rdfs:label  ?place__label_value
        FILTER ( lang(?place__label_value) = "mul" )
      }
    BIND(if(bound(?place__label_value), ?place__label_value, if(( isURI(?place) && strstarts(str(?place), "http://www.wikidata.org/entity/") ), strafter(str(?place), "entity/"), str(?place))) AS ?label)
  }

# Original query:
# #defaultView:Map
# SELECT ?label ?coord ?place ?image
# WHERE {
# 	?place wdt:P31 wd:Q14276458 ;  # instance of deck arch bridge
#             wdt:P186 wd:Q22731 ;  # made of stone
#             wdt:P625 ?coord .
# 	OPTIONAL { ?place wdt:P18 ?image }
# SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en".
#                         ?place rdfs:label ?label }
# }
