# rewrite_status: rewritten
#title: Countries sorted by population
# defaultView:BubbleChart
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT  ?countryLabel ?population
WHERE
  { ?country  wdt:P31    wd:Q6256 ;
              wdt:P1082  ?population
    OPTIONAL
      { ?country  rdfs:label  ?country__label_value
        FILTER ( lang(?country__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?country  rdfs:label  ?country__label_value
        FILTER ( lang(?country__label_value) = "mul" )
      }
    OPTIONAL
      { ?country  rdfs:label  ?country__label_value
        FILTER ( lang(?country__label_value) = "en" )
      }
    BIND(if(bound(?country__label_value), ?country__label_value, if(( isURI(?country) && strstarts(str(?country), "http://www.wikidata.org/entity/") ), strafter(str(?country), "entity/"), str(?country))) AS ?countryLabel)
  }
GROUP BY ?population ?countryLabel
ORDER BY DESC(?population)

# Original query:
# #title: Countries sorted by population
# # defaultView:BubbleChart
# SELECT DISTINCT ?countryLabel ?population
# {
#   ?country wdt:P31 wd:Q6256 ;
#            wdt:P1082 ?population .
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" }
# }
# GROUP BY ?population ?countryLabel
# ORDER BY DESC(?population)
