# rewrite_status: rewritten
#added before 2016-10
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  schema: <http://schema.org/>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>

SELECT  ?item ?itemLabel (COUNT(DISTINCT ?sitelink) AS ?count)
WHERE
  { ?item     wdt:P31       wd:Q5 ;
              wdt:P27       wd:Q142 .
    ?sitelink  schema:about  ?item
    FILTER EXISTS { ?wen  schema:about       ?item ;
                          schema:inLanguage  "en"
                  }
    FILTER NOT EXISTS { ?wfr  schema:about       ?item ;
                              schema:inLanguage  "fr"
                      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "fr" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "en" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "mul" )
      }
    BIND(if(bound(?item__label_value), ?item__label_value, if(( isURI(?item) && strstarts(str(?item), "http://www.wikidata.org/entity/") ), strafter(str(?item), "entity/"), str(?item))) AS ?itemLabel)
  }
GROUP BY ?item ?itemLabel
ORDER BY DESC(?count)

# Original query:
# #added before 2016-10
# SELECT ?item ?itemLabel (COUNT(distinct ?sitelink) as ?count)
# WHERE
# {
# 	?item wdt:P31 wd:Q5 .
# 	?item wdt:P27 wd:Q142 .
# 	?sitelink schema:about ?item .
# 	FILTER EXISTS { ?wen schema:about ?item . ?wen schema:inLanguage "en" }
# 	FILTER NOT EXISTS { ?wfr schema:about ?item . ?wfr schema:inLanguage "fr" }
# 	SERVICE wikibase:label {
# 		bd:serviceParam wikibase:language "fr,en" .
# 	}
# }
# GROUP BY ?item ?itemLabel
# ORDER BY DESC(?count)
