# rewrite_status: rewritten
#title: Female scientists with most number of sitelinks (but not English Wikipedia)

#PREFIX schema: <http://schema.org/>

PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  schema: <http://schema.org/>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>
PREFIX  wikibase: <http://wikiba.se/ontology#>

SELECT  ?item ?itemLabel ?linkcount
WHERE
  { ?item  wdt:P31             wd:Q5 ;
           wdt:P21             wd:Q6581072 ;
           wdt:P106            wd:Q901 ;
           wikibase:sitelinks  ?linkcount
    FILTER ( ?linkcount >= 1 )
    FILTER NOT EXISTS { ?article  schema:about       ?item ;
                                  schema:inLanguage  "en" ;
                                  schema:isPartOf    <https://en.wikipedia.org/>
                      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "en" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "de" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "es" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "ar" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "fr" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "mul" )
      }
    BIND(if(bound(?item__label_value), ?item__label_value, if(( isURI(?item) && strstarts(str(?item), "http://www.wikidata.org/entity/") ), strafter(str(?item), "entity/"), str(?item))) AS ?itemLabel)
  }
GROUP BY ?item ?itemLabel ?linkcount
ORDER BY DESC(?linkcount)

# Original query:
# #title: Female scientists with most number of sitelinks (but not English Wikipedia)
#
# #PREFIX schema: <http://schema.org/>
#
# SELECT ?item ?itemLabel ?linkcount WHERE {
#     ?item wdt:P31 wd:Q5 .
#     ?item wdt:P21 wd:Q6581072 .
#     ?item wdt:P106 wd:Q901 .
#     ?item wikibase:sitelinks ?linkcount .
#   FILTER (?linkcount >= 1) . # only include items with 1 or more sitelinks
#   FILTER NOT EXISTS {
#     ?article schema:about ?item .
#     ?article schema:inLanguage "en" .
#     ?article schema:isPartOf <https://en.wikipedia.org/>
#   }
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "en,de,es,ar,fr" }
# }
# GROUP BY ?item ?itemLabel ?linkcount
# ORDER BY DESC(?linkcount)
