# rewrite_status: rewritten
#title: Using VALUES for extracting scientific articles of specific authors
#  NOTE - This scholarly query is written for use in WDQS-Main UI only  (query.wikidata.org).

PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>

SELECT  ?entity ?entityLabel ?authorLabel
WHERE
  { SERVICE <https://query-scholarly-next.wikidata.org/sparql>
      { SELECT  ?entity ?entityLabel ?author
        WHERE
          { VALUES ?author { wd:Q18016466 }
            ?entity  wdt:P31  wd:Q13442814 ;
                     wdt:P50  ?author
            OPTIONAL
              { ?entity  rdfs:label  ?entity__label_value
                FILTER ( lang(?entity__label_value) = "[AUTO_LANGUAGE]" )
              }
            OPTIONAL
              { ?entity  rdfs:label  ?entity__label_value
                FILTER ( lang(?entity__label_value) = "mul" )
              }
            OPTIONAL
              { ?entity  rdfs:label  ?entity__label_value
                FILTER ( lang(?entity__label_value) = "en" )
              }
            BIND(if(bound(?entity__label_value), ?entity__label_value, if(( isURI(?entity) && strstarts(str(?entity), "http://www.wikidata.org/entity/") ), strafter(str(?entity), "entity/"), str(?entity))) AS ?entityLabel)
          }
      }
    OPTIONAL
      { ?author  rdfs:label  ?author__label_value
        FILTER ( lang(?author__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?author  rdfs:label  ?author__label_value
        FILTER ( lang(?author__label_value) = "mul" )
      }
    OPTIONAL
      { ?author  rdfs:label  ?author__label_value
        FILTER ( lang(?author__label_value) = "en" )
      }
    BIND(if(bound(?author__label_value), ?author__label_value, if(( isURI(?author) && strstarts(str(?author), "http://www.wikidata.org/entity/") ), strafter(str(?author), "entity/"), str(?author))) AS ?authorLabel)
  }

# Original query:
# #title: Using VALUES for extracting scientific articles of specific authors
# #  NOTE - This scholarly query is written for use in WDQS-Main UI only  (query.wikidata.org).
#
#  SELECT ?entity ?entityLabel ?authorLabel WHERE {
#   hint:Query hint:optimizer "None".
#   SERVICE wdsubgraph:scholarly_articles {
#     SELECT ?entity ?entityLabel ?author WHERE {
#       VALUES ?author {wd:Q18016466} #initialize "?author with the Wikidata item "Lydia Pintscher"
#       ?entity wdt:P31 wd:Q13442814. #filter by scientific articles
#       ?entity wdt:P50 ?author.
#       SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
#     }
#    }
#  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
# }
