# rewrite_status: rewritten
#title: Featured articles of all Wikimedia projects
# Get all Featured Articles (Q17437796)
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  schema: <http://schema.org/>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wikibase: <http://wikiba.se/ontology#>

SELECT  ?lang ?name ?itemLabel ?sitelink ?linkcount ?item
WHERE
  { ?item     wikibase:sitelinks  ?linkcount .
    ?sitelink  schema:name        ?name ;
              schema:inLanguage   ?lang ;
              schema:about        ?item ;
              wikibase:badge      wd:Q17437796
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "mul" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "en" )
      }
    BIND(if(bound(?item__label_value), ?item__label_value, if(( isURI(?item) && strstarts(str(?item), "http://www.wikidata.org/entity/") ), strafter(str(?item), "entity/"), str(?item))) AS ?itemLabel)
  }

# Original query:
# #title: Featured articles of all Wikimedia projects
# # Get all Featured Articles (Q17437796)
# SELECT ?lang ?name ?itemLabel ?sitelink ?linkcount ?item WHERE {
#   ?item wikibase:sitelinks ?linkcount.
#   ?sitelink schema:name ?name;
#     schema:inLanguage ?lang;
#     schema:about ?item;
#     # Sitelink is badged as a Featured Article
#     wikibase:badge wd:Q17437796.
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
# }
