# rewrite_status: rewritten
#title: Mountains over 8000 meters elevation
#updated 2021-04-25
#defaultView:Map
PREFIX  p:    <http://www.wikidata.org/prop/>
PREFIX  psn:  <http://www.wikidata.org/prop/statement/value-normalized/>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  schema: <http://schema.org/>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>
PREFIX  wikibase: <http://wikiba.se/ontology#>

SELECT  ?item ?itemLabel ?itemDescription ?coord ?elevation
WHERE
  { ?item  wdt:P31  wd:Q8502 ;
           p:P2044  _:b0 .
    _:b0   a        wikibase:BestRank .
    _:b0 psn:P2044/wikibase:quantityAmount ?elevation
    FILTER ( ?elevation >= 8000 )
    ?item  wdt:P625  ?coord
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "mul" )
      }
    OPTIONAL
      { ?item  rdfs:label  ?item__label_value
        FILTER ( lang(?item__label_value) = "en" )
      }
    BIND(if(bound(?item__label_value), ?item__label_value, if(( isURI(?item) && strstarts(str(?item), "http://www.wikidata.org/entity/") ), strafter(str(?item), "entity/"), str(?item))) AS ?itemLabel)
    OPTIONAL
      { ?item  schema:description  ?item__description_value
        FILTER ( lang(?item__description_value) = "[AUTO_LANGUAGE]" )
      }
    OPTIONAL
      { ?item  schema:description  ?item__description_value
        FILTER ( lang(?item__description_value) = "en" )
      }
    BIND(?item__description_value AS ?itemDescription)
  }

# Original query:
# #title: Mountains over 8000 meters elevation
# #updated 2021-04-25
# #defaultView:Map
# SELECT ?item ?itemLabel ?itemDescription ?coord ?elevation
# WHERE
# {
#   ?item wdt:P31 wd:Q8502 .
#   ?item p:P2044 [ a wikibase:BestRank; psn:P2044/wikibase:quantityAmount ?elevation ]
#   FILTER(?elevation >= 8000 )
#   ?item wdt:P625 ?coord.
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" }
# }
